### ISSUE TITLE
Can't send notifications with win64 version

### ISSUE THREAD

**Issue by gkobler** [DelphiWorlds/PushIt#2]
When I send messages with the Win32 version it works fine, but when I try to send messages with the same settings with the Win64 version I get the following message 

`Error - PostFailure: 403: Forbidden - {
  "error": {
    "code": 403,
    "message": "Permission 'cloudmessaging.messages.create' denied on resource '//cloudresourcemanager.googleapis.com/projects/myprojects' (or it may not exist).",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "IAM_PERMISSION_DENIED",
        "domain": "cloudresourcemanager.googleapis.com",
        "metadata": {
          "resource": "projects/myprojects",
          "permission": "cloudmessaging.messages.create"
        }
      }
    ]
  }
}
 - {"message":{"token":"mytoken","notification":{"title":"Testmessage","body":"Testbody"},"apns":{"payload":{"aps":{"badge":0,"mutable-content":1}}}}}`

**Comment by gkobler** [comment]
Meanwhile i got a solution, when you change the servicve account JSON file you have to restart the App, otherwise the "old" settings will be taken

**Comment by DelphiWorlds** [comment]
> Meanwhile i got a solution, when you change the servicve account JSON file you have to restart the App, otherwise the "old" settings will be taken

Please list the steps to reproduce this.

**Comment by gkobler** [comment]
1. Load a JSON file for the service account with no granted access the press send, you will see the error
2. Load a JSON file witch has access, press send the error will be apear
3. restart the program, and press send again, it will work

**Comment by DelphiWorlds** [comment]
I'm unable to reproduce the issue using the given steps - at step 2, sending is successful

**Comment by DelphiWorlds** [comment]
Closed due to no response
